services:
  - type: web
    name: library-management-system
    env: docker
    region: oregon
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://+:8080
      - key: ConnectionStrings__DefaultConnection
        fromDatabase:
          name: library-db
          property: connectionString
      - key: Jwt__Key
        generateValue: true
      - key: Jwt__Issuer
        value: LibraryManagementSystemAPI
      - key: Jwt__Audience
        value: LibraryManagementSystemClient
      - key: AllowedOrigins__0
        value: https://library-management-system.onrender.com

databases:
  - name: library-db
    databaseName: librarydb
    plan: free
    region: oregon
